/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface WtrButton {
    'color': 'default' | 'primary' | 'secondary' | undefined;
    'type': 'button' | 'submit' | undefined;
    'variant': 'text' | 'outlined' | 'contained' | undefined;
  }
  interface WtrContainer {}
  interface WtrHeader {
    'darkMode': boolean;
    'nav': boolean;
  }
  interface WtrRoot {}
  interface WtrTextfield {
    'label': string;
    'name': string;
    'type': 'text' | 'password' | 'email' | undefined;
    'value': string;
  }
  interface WtrTypography {
    'variant': 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'p' | undefined;
  }
}

declare global {


  interface HTMLWtrButtonElement extends Components.WtrButton, HTMLStencilElement {}
  var HTMLWtrButtonElement: {
    prototype: HTMLWtrButtonElement;
    new (): HTMLWtrButtonElement;
  };

  interface HTMLWtrContainerElement extends Components.WtrContainer, HTMLStencilElement {}
  var HTMLWtrContainerElement: {
    prototype: HTMLWtrContainerElement;
    new (): HTMLWtrContainerElement;
  };

  interface HTMLWtrHeaderElement extends Components.WtrHeader, HTMLStencilElement {}
  var HTMLWtrHeaderElement: {
    prototype: HTMLWtrHeaderElement;
    new (): HTMLWtrHeaderElement;
  };

  interface HTMLWtrRootElement extends Components.WtrRoot, HTMLStencilElement {}
  var HTMLWtrRootElement: {
    prototype: HTMLWtrRootElement;
    new (): HTMLWtrRootElement;
  };

  interface HTMLWtrTextfieldElement extends Components.WtrTextfield, HTMLStencilElement {}
  var HTMLWtrTextfieldElement: {
    prototype: HTMLWtrTextfieldElement;
    new (): HTMLWtrTextfieldElement;
  };

  interface HTMLWtrTypographyElement extends Components.WtrTypography, HTMLStencilElement {}
  var HTMLWtrTypographyElement: {
    prototype: HTMLWtrTypographyElement;
    new (): HTMLWtrTypographyElement;
  };
  interface HTMLElementTagNameMap {
    'wtr-button': HTMLWtrButtonElement;
    'wtr-container': HTMLWtrContainerElement;
    'wtr-header': HTMLWtrHeaderElement;
    'wtr-root': HTMLWtrRootElement;
    'wtr-textfield': HTMLWtrTextfieldElement;
    'wtr-typography': HTMLWtrTypographyElement;
  }
}

declare namespace LocalJSX {
  interface WtrButton {
    'color'?: 'default' | 'primary' | 'secondary' | undefined;
    'type'?: 'button' | 'submit' | undefined;
    'variant'?: 'text' | 'outlined' | 'contained' | undefined;
  }
  interface WtrContainer {}
  interface WtrHeader {
    'darkMode'?: boolean;
    'nav'?: boolean;
    'onLoggedOut'?: (event: CustomEvent<any>) => void;
    'onToggleDarkMode'?: (event: CustomEvent<any>) => void;
  }
  interface WtrRoot {}
  interface WtrTextfield {
    'label'?: string;
    'name'?: string;
    'onHandleInput'?: (event: CustomEvent<any>) => void;
    'type'?: 'text' | 'password' | 'email' | undefined;
    'value'?: string;
  }
  interface WtrTypography {
    'variant'?: 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'p' | undefined;
  }

  interface IntrinsicElements {
    'wtr-button': WtrButton;
    'wtr-container': WtrContainer;
    'wtr-header': WtrHeader;
    'wtr-root': WtrRoot;
    'wtr-textfield': WtrTextfield;
    'wtr-typography': WtrTypography;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'wtr-button': LocalJSX.WtrButton & JSXBase.HTMLAttributes<HTMLWtrButtonElement>;
      'wtr-container': LocalJSX.WtrContainer & JSXBase.HTMLAttributes<HTMLWtrContainerElement>;
      'wtr-header': LocalJSX.WtrHeader & JSXBase.HTMLAttributes<HTMLWtrHeaderElement>;
      'wtr-root': LocalJSX.WtrRoot & JSXBase.HTMLAttributes<HTMLWtrRootElement>;
      'wtr-textfield': LocalJSX.WtrTextfield & JSXBase.HTMLAttributes<HTMLWtrTextfieldElement>;
      'wtr-typography': LocalJSX.WtrTypography & JSXBase.HTMLAttributes<HTMLWtrTypographyElement>;
    }
  }
}


